### PR TITLE
FIX - packaging.type property is breaking various build systems (sbt, gradle, ivy, etc.)

### PR DESCRIPTION
**Pull request by Randgalt**
This has been discussed here #571 and and #572. This has not been fixed - there is no workaround for sbt. PLEASE fix this as it causing a great deal of problem for users. Further, there appears to be no good reason for the change.

### CODE REVIEW

**Comment by pavelbucek** [comment]
Hi Rangalt,

you'd need to sign the OCA to be able to contribute, see http://www.oracle.com/technetwork/community/oca-486395.html

also, proposed change is not a proper fix, if you'd evaluate the pom file more carefuly, you'd notice that the packaging type for jdk8 and older is `bundle`.

I'm not sure whether I stated this only in private messages with other involved people, but let me state this again - I'm really sorry this causes issues for ivy and gradle users, but the issue is not in this pom file. It is in the way how ivy/gradle consumes maven artifacts. Seems like authors of maven plugins choose to evaluate pom files DIFFERENTLY than maven and this is a price. I would suggest to file a bug or pull request against gradle maven plugin (and I believe Ivy just reuses the same code).

JAX-RS pom file is ok from pom file spec side - it is perfectly usable from maven.

I'm closing this PR for now.

Regards,
Pavel

**Comment by Randgalt** [comment]
> JAX-RS pom file is ok from pom file spec side - it is perfectly usable from maven.

So, you're happy to produce an artifact that can only be consumed from Maven? Shame. This is a *real* problem for a lot of users. You are doing a major disservice to the community.

**Comment by pavelbucek** [comment]
>> JAX-RS pom file is ok from pom file spec side - it is perfectly usable from maven.

> So, you're happy to produce an artifact that can only be consumed from Maven? Shame. This is a real  problem for a lot of users. You are doing a major disservice to the community.

I'm happy to produce valid maven artifact. Please think about the consequences - what if ivy maven parser at some point break so bad that it won't be able to use <properties> from pom files at all - will you then "ask" everyone to stop using maven properties?

I would suggest that you could spend your energy to fixing the issue on ivy side. And thanks for nice words about myself, hope you are feeling better now.

**Comment by xerial** [comment]
@pavelbucek 
I understand this is not an issue of jax-rs/api side, however, because of the use of `${packaging.type}` in packaging element, sbt and gradle users have suffered inconvenience.

I guess one of the reason why people got so angry here is you are closing related tickets (#571, #572, #576, etc.) so quickly and giving an wrong impression that this problem is already solved while it is not solved at all for these people. By reading these related tickets, we can see you have no intention to solve this issue in your side, and we feel totally rejected.

For people suffering from this issue, I would like to leave some pointers:
- For sbt-1.0.x, we already have a workaround https://github.com/sbt/sbt/issues/3618
- Gradle may need more work to provide a workaround: https://github.com/gradle/gradle/issues/3065

**Comment by Randgalt** [comment]
FWIW - that sbt "fix" does not work for us. Our only work around is to add "-Dpackaging.type=jar" to our command line everywhere.

**Comment by francisdb** [comment]
@Randgalt you might also want to try the coursier sbt plugin that does not have this issue
https://github.com/coursier/coursier

**Comment by jaikiran** [comment]
FWIW - this got reported in Ivy issue tracker[1] recently. A potential fix has been made in Ivy upstream and the nightly build of Ivy can be tested to make sure this works for those running into this issue in Ivy. Details on how to get the Ivy nightly build is available in the linked JIRA[1].

[1] https://issues.apache.org/jira/browse/IVY-1577

**Pull request closed without merging**
